### ISSUE TITLE
Push release tags to GitHub

### ISSUE THREAD

**Issue by artob** [ForeverZer0/glfw#2]
This project has several [releases on RubyGems](https://rubygems.org/gems/glfw), but no release tags on GitHub. Perhaps a quick `git push --tags` would be a good thing to do?

**Comment by ForeverZer0** [comment]
Good idea, I have been lazy with giving this project any attention lately.
Will do when I get on my dev machine where local repo is at.

**Comment by artob** [comment]
It's a cool project, and works well :+1:

**Comment by ForeverZer0** [comment]
Pushed a tag for latest version, apparently I was not too keen on tagging during development, as no others exist :P
